//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denion.Web.ProviderClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Replace")]
        public string SqlServer {
            get {
                return ((string)(this["SqlServer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://verwijsindex.shpv.nl/Service/VerwijsIndexService.svc")]
        public string ProviderServiceURL {
            get {
                return ((string)(this["ProviderServiceURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<s:Envelope xmlns:s=""http://www.w3.org/2003/05/soap-envelope"" xmlns:a=""http://www.w3.org/2005/08/addressing"">
  <s:Header>
    <a:Action s:mustUnderstand=""1"">https://verwijsindex.shpv.nl/service/Provider/BatchRegistration</a:Action>
    <a:MessageID>urn:uuid:<!--MessageID--></a:MessageID>
    <a:ReplyTo>
      <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
    </a:ReplyTo>
    <a:To s:mustUnderstand=""1""><!--To--></a:To>
  </s:Header>
  <s:Body>
    <BatchRegistration xmlns=""https://verwijsindex.shpv.nl/service/"">
      <req xmlns:b=""https://verwijsindex.shpv.nl/messages/"" xmlns:i=""http://www.w3.org/2001/XMLSchema-instance"">
        <b:Batch>
          <!--LinkRegistrationRequest-->
        </b:Batch>
      </req>
    </BatchRegistration>
  </s:Body>
</s:Envelope>")]
        public string LinkRegistrationRequestContainer {
            get {
                return ((string)(this["LinkRegistrationRequestContainer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"          <b:LinkRegistrationRequest>
            <b:ProviderId><!--ProviderId--></b:ProviderId>
            <b:LinkId><!--LinkId--></b:LinkId>
            <b:VehicleId><!--VehicleId--></b:VehicleId>
            <b:CountryCode><!--CountryCode--></b:CountryCode>
            <b:ValidFrom><!--ValidFrom--></b:ValidFrom>
            <b:ValidUntil><!--ValidUntil--></b:ValidUntil>
          </b:LinkRegistrationRequest>")]
        public string LinkRegistrationRequestMessage {
            get {
                return ((string)(this["LinkRegistrationRequestMessage"]));
            }
        }
    }
}
