//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Denion.WebService.VerwijsIndex.Prod {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://verwijsindex.shpv.nl/service/", ConfigurationName="Prod.VerwijsIndex")]
    public interface VerwijsIndex {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://verwijsindex.shpv.nl/service/VerwijsIndex/PaymentStart", ReplyAction="https://verwijsindex.shpv.nl/service/VerwijsIndex/PaymentStartResponse")]
        Denion.WebService.VerwijsIndex.PaymentStartResponse PaymentStart(Denion.WebService.VerwijsIndex.PaymentStartRequest PaymentStartRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://verwijsindex.shpv.nl/service/VerwijsIndex/PaymentEnd", ReplyAction="https://verwijsindex.shpv.nl/service/VerwijsIndex/PaymentEndResponse")]
        Denion.WebService.VerwijsIndex.PaymentEndResponse PaymentEnd(Denion.WebService.VerwijsIndex.PaymentEndRequest PaymentEndRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://verwijsindex.shpv.nl/service/VerwijsIndex/PaymentCheck", ReplyAction="https://verwijsindex.shpv.nl/service/VerwijsIndex/PaymentCheckResponse")]
        Denion.WebService.VerwijsIndex.PaymentCheckResponse PaymentCheck(Denion.WebService.VerwijsIndex.PaymentCheckRequest PaymentCheckRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VerwijsIndexChannel : Denion.WebService.VerwijsIndex.Prod.VerwijsIndex, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerwijsIndexClient : System.ServiceModel.ClientBase<Denion.WebService.VerwijsIndex.Prod.VerwijsIndex>, Denion.WebService.VerwijsIndex.Prod.VerwijsIndex {
        
        public VerwijsIndexClient() {
        }
        
        public VerwijsIndexClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerwijsIndexClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerwijsIndexClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerwijsIndexClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Denion.WebService.VerwijsIndex.PaymentStartResponse PaymentStart(Denion.WebService.VerwijsIndex.PaymentStartRequest PaymentStartRequest) {
            return base.Channel.PaymentStart(PaymentStartRequest);
        }
        
        public Denion.WebService.VerwijsIndex.PaymentEndResponse PaymentEnd(Denion.WebService.VerwijsIndex.PaymentEndRequest PaymentEndRequest) {
            return base.Channel.PaymentEnd(PaymentEndRequest);
        }
        
        public Denion.WebService.VerwijsIndex.PaymentCheckResponse PaymentCheck(Denion.WebService.VerwijsIndex.PaymentCheckRequest PaymentCheckRequest) {
            return base.Channel.PaymentCheck(PaymentCheckRequest);
        }
    }
}
