//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTestTool.shpv.nl_MonitorService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Models.CheckResultCollectionOfModels.VWXInfo_PerPeriodczrXvgmi", Namespace="http://schemas.datacontract.org/2004/07/Monitor.VWX.Imported")]
    [System.SerializableAttribute()]
    public partial class ModelsCheckResultCollectionOfModelsVWXInfo_PerPeriodczrXvgmi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceTestTool.shpv.nl_MonitorService.ModelsVWXInfo_PerPeriod[] collectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceTestTool.shpv.nl_MonitorService.ModelsVWXInfo_PerPeriod[] collection {
            get {
                return this.collectionField;
            }
            set {
                if ((object.ReferenceEquals(this.collectionField, value) != true)) {
                    this.collectionField = value;
                    this.RaisePropertyChanged("collection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Models.VWXInfo_PerPeriod", Namespace="http://schemas.datacontract.org/2004/07/Monitor.VWX.Imported")]
    [System.SerializableAttribute()]
    public partial class ModelsVWXInfo_PerPeriod : WebServiceTestTool.shpv.nl_MonitorService.ModelsDurationInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End {
            get {
                return this.EndField;
            }
            set {
                if ((this.EndField.Equals(value) != true)) {
                    this.EndField = value;
                    this.RaisePropertyChanged("End");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Function {
            get {
                return this.FunctionField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionField, value) != true)) {
                    this.FunctionField = value;
                    this.RaisePropertyChanged("Function");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Models.DurationInfo", Namespace="http://schemas.datacontract.org/2004/07/Monitor.VWX.Imported")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServiceTestTool.shpv.nl_MonitorService.ModelsIISInfo_PerPeriod))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WebServiceTestTool.shpv.nl_MonitorService.ModelsVWXInfo_PerPeriod))]
    public partial class ModelsDurationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConsumedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Consumed {
            get {
                return this.ConsumedField;
            }
            set {
                if ((this.ConsumedField.Equals(value) != true)) {
                    this.ConsumedField = value;
                    this.RaisePropertyChanged("Consumed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Start {
            get {
                return this.StartField;
            }
            set {
                if ((this.StartField.Equals(value) != true)) {
                    this.StartField = value;
                    this.RaisePropertyChanged("Start");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Models.IISInfo_PerPeriod", Namespace="http://schemas.datacontract.org/2004/07/Monitor.VWX.Imported")]
    [System.SerializableAttribute()]
    public partial class ModelsIISInfo_PerPeriod : WebServiceTestTool.shpv.nl_MonitorService.ModelsDurationInfo {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationUriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationUri {
            get {
                return this.DestinationUriField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationUriField, value) != true)) {
                    this.DestinationUriField = value;
                    this.RaisePropertyChanged("DestinationUri");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Models.CheckResultCollectionOfModels.IISInfo_PerPeriodczrXvgmi", Namespace="http://schemas.datacontract.org/2004/07/Monitor.VWX.Imported")]
    [System.SerializableAttribute()]
    public partial class ModelsCheckResultCollectionOfModelsIISInfo_PerPeriodczrXvgmi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebServiceTestTool.shpv.nl_MonitorService.ModelsIISInfo_PerPeriod[] collectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebServiceTestTool.shpv.nl_MonitorService.ModelsIISInfo_PerPeriod[] collection {
            get {
                return this.collectionField;
            }
            set {
                if ((object.ReferenceEquals(this.collectionField, value) != true)) {
                    this.collectionField = value;
                    this.RaisePropertyChanged("collection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusInfo", Namespace="http://schemas.datacontract.org/2004/07/Monitor.VWX.Imported")]
    [System.SerializableAttribute()]
    public partial class StatusInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName {
            get {
                return this.ServiceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceNameField, value) != true)) {
                    this.ServiceNameField = value;
                    this.RaisePropertyChanged("ServiceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="shpv.nl_MonitorService.IMonitorVWX")]
    public interface IMonitorVWX {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorVWX/GetVWXPerPeriodRecords", ReplyAction="http://tempuri.org/IMonitorVWX/GetVWXPerPeriodRecordsResponse")]
        WebServiceTestTool.shpv.nl_MonitorService.ModelsCheckResultCollectionOfModelsVWXInfo_PerPeriodczrXvgmi GetVWXPerPeriodRecords(string periodStart, string periodEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorVWX/GetIISPerPeriodRecords", ReplyAction="http://tempuri.org/IMonitorVWX/GetIISPerPeriodRecordsResponse")]
        WebServiceTestTool.shpv.nl_MonitorService.ModelsCheckResultCollectionOfModelsIISInfo_PerPeriodczrXvgmi GetIISPerPeriodRecords(string periodStart, string periodEnd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitorVWX/GetServiceStatus", ReplyAction="http://tempuri.org/IMonitorVWX/GetServiceStatusResponse")]
        WebServiceTestTool.shpv.nl_MonitorService.StatusInfo GetServiceStatus();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitorVWXChannel : WebServiceTestTool.shpv.nl_MonitorService.IMonitorVWX, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorVWXClient : System.ServiceModel.ClientBase<WebServiceTestTool.shpv.nl_MonitorService.IMonitorVWX>, WebServiceTestTool.shpv.nl_MonitorService.IMonitorVWX {
        
        public MonitorVWXClient() {
        }
        
        public MonitorVWXClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorVWXClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorVWXClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorVWXClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebServiceTestTool.shpv.nl_MonitorService.ModelsCheckResultCollectionOfModelsVWXInfo_PerPeriodczrXvgmi GetVWXPerPeriodRecords(string periodStart, string periodEnd) {
            return base.Channel.GetVWXPerPeriodRecords(periodStart, periodEnd);
        }
        
        public WebServiceTestTool.shpv.nl_MonitorService.ModelsCheckResultCollectionOfModelsIISInfo_PerPeriodczrXvgmi GetIISPerPeriodRecords(string periodStart, string periodEnd) {
            return base.Channel.GetIISPerPeriodRecords(periodStart, periodEnd);
        }
        
        public WebServiceTestTool.shpv.nl_MonitorService.StatusInfo GetServiceStatus() {
            return base.Channel.GetServiceStatus();
        }
    }
}
